name: JFrog
run-name: Testing JFrog Integration
on: [push, workflow_dispatch]
jobs:
  Artifactory-Scan:
    runs-on: self-hosted
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3.3.0