name: Unit-Test
run-name: Run Unit Tests
on: [push, workflow_dispatch]
jobs:
  Run-Unit-Tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package